const emojiMap = {
    ":smile:": "😄",
    ":laughing:": "😆",
    ":blush:": "😊",
    ":smiley:": "😃",
    ":relaxed:": "☺️",
    ":smirk:": "😏",
    ":heart_eyes:": "😍",
    ":kissing_heart:": "😘",
    ":kissing_closed_eyes:": "😚",
    ":flushed:": "😳",
    ":relieved:": "😌",
    ":satisfied:": "😆",
    ":grin:": "😁",
    ":wink:": "😉",
    ":middle_finger:": "🖕",
    ":stuck_out_tongue_winking_eye:": "😜",
    ":stuck_out_tongue_closed_eyes:": "😝",
    ":grinning:": "😀",
    ":kissing:": "😗",
    ":kissing_smiling_eyes:": "😙",
    ":stuck_out_tongue:": "😛",
    ":sleeping:": "😴",
    ":worried:": "😟",
    ":frowning:": "😦",
    ":anguished:": "😧",
    ":open_mouth:": "😮",
    ":grimacing:": "😬",
    ":confused:": "😕",
    ":hushed:": "😯",
    ":expressionless:": "😑",
    ":unamused:": "😒",
    ":sweat_smile:": "😅",
    ":sweat:": "😓",
    ":disappointed_relieved:": "😥",
    ":weary:": "😩",
    ":pensive:": "😔",
    ":disappointed:": "😞",
    ":confounded:": "😖",
    ":fearful:": "😨",
    ":cold_sweat:": "😰",
    ":persevere:": "😣",
    ":cry:": "😢",
    ":sob:": "😭",
    ":joy:": "😂",
    ":astonished:": "😲",
    ":scream:": "😱",
    ":tired_face:": "😫",
    ":angry:": "😠",
    ":rage:": "😡",
    ":triumph:": "😤",
    ":sleepy:": "😪",
    ":yum:": "😋",
    ":mask:": "😷",
    ":sunglasses:": "😎",
    ":dizzy_face:": "😵",
    ":imp:": "👿",
    ":smiling_imp:": "😈",
    ":neutral_face:": "😐",
    ":no_mouth:": "😶",
    ":heart:": "❤️",
    ":yellow_heart:": "💛",
    ":blue_heart:": "💙",
    ":purple_heart:": "💜",
    ":green_heart:": "💚",
    ":broken_heart:": "💔",
    ":star:": "⭐",
    ":sparkles:": "✨",
    ":zap:": "⚡",
    ":fire:": "🔥",
    ":thumbsup:": "👍",
    ":thumbsdown:": "👎",
    ":ok_hand:": "👌",
    ":punch:": "👊",
    ":v:": "✌️",
    ":wave:": "👋",
    ":raised_hand:": "✋",
    ":eyes:": "👀",
    ":ear:": "👂",
    ":nose:": "👃",
    ":lips:": "👄",
    ":tongue:": "👅",
    ":clap:": "👏",
    ":pray:": "🙏",
    ":dog:": "🐶",
    ":cat:": "🐱",
    ":mouse:": "🐭",
    ":hamster:": "🐹",
    ":rabbit:": "🐰",
    ":fox:": "🦊",
    ":bear:": "🐻",
    ":panda:": "🐼",
    ":tiger:": "🐯",
    ":lion:": "🦁",
    ":cow:": "🐮",
    ":pig:": "🐷",
    ":apple:": "🍎",
    ":pizza:": "🍕",
    ":hamburger:": "🍔",
    ":fries:": "🍟",
    ":sushi:": "🍣",
    ":coffee:": "☕",
    ":beer:": "🍺",
    ":wine_glass:": "🍷",
    ":cake:": "🍰",
    ":sunny:": "☀️",
    ":cloud:": "☁️",
    ":umbrella:": "☔",
    ":snowflake:": "❄️",
    ":rainbow:": "🌈",
    ":earth:": "🌎",
    ":moon:": "🌙",
    ":star2:": "🌟",
    // New facial expressions and emotions
    ":smiling_face_with_tear:": "🥲",
    ":pleading_face:": "🥺",
    ":face_with_raised_eyebrow:": "🤨",
    ":face_with_monocle:": "🧐",
    ":partying_face:": "🥳",
    ":woozy_face:": "🥴",
    ":hot_face:": "🥵",
    ":cold_face:": "🥶",
    ":face_vomiting:": "🤮",
    ":exploding_head:": "🤯",
    ":cowboy:": "🤠",
    ":face_with_symbols_on_mouth:": "🤬",
    // New hand gestures
    ":point_up:": "👆",
    ":point_down:": "👇",
    ":point_left:": "👈",
    ":point_right:": "👉",
    ":fist:": "✊",
    ":crossed_fingers:": "🤞",
    ":love_you_gesture:": "🤟",
    ":call_me_hand:": "🤙",
    ":pinched_fingers:": "🤌",
    ":pinching_hand:": "🤏",
    // New people and roles
    ":person_walking:": "🚶",
    ":person_running:": "🏃",
    ":dancer:": "💃",
    ":person_swimming:": "🏊",
    ":person_lifting_weights:": "🏋️",
    ":person_biking:": "🚴",
    ":artist:": "🎨",
    ":astronaut:": "👩‍🚀",
    ":firefighter:": "👩‍🚒",
    ":doctor:": "👩‍⚕️",
    ":teacher:": "👩‍🏫",
    // New animals
    ":elephant:": "🐘",
    ":rhino:": "🦏",
    ":hippo:": "🦛",
    ":giraffe:": "🦒",
    ":zebra:": "🦓",
    ":deer:": "🦌",
    ":camel:": "🐫",
    ":horse:": "🐎",
    ":sheep:": "🐑",
    ":goat:": "🐐",
    ":snake:": "🐍",
    ":bird:": "🐦",
    ":penguin:": "🐧",
    ":peacock:": "🦚",
    ":parrot:": "🦜",
    ":fish:": "🐟",
    ":dolphin:": "🐬",
    ":whale:": "🐳",
    ":shark:": "🦈",
    ":crocodile:": "🐊",
    ":butterfly:": "🦋",
    ":bee:": "🐝",
    ":ladybug:": "🐞",
    // New food and drink
    ":banana:": "🍌",
    ":orange:": "🍊",
    ":grapes:": "🍇",
    ":strawberry:": "🍓",
    ":watermelon:": "🍉",
    ":pineapple:": "🍍",
    ":mango:": "🥭",
    ":peach:": "🍑",
    ":cherries:": "🍒",
    ":avocado:": "🥑",
    ":carrot:": "🥕",
    ":corn:": "🌽",
    ":broccoli:": "🥦",
    ":tomato:": "🍅",
    ":eggplant:": "🍆",
    ":bread:": "🍞",
    ":cheese:": "🧀",
    ":bacon:": "🥓",
    ":pancakes:": "🥞",
    ":egg:": "🥚",
    ":ice_cream:": "🍦",
    ":doughnut:": "🍩",
    ":tea:": "🍵",
    ":juice:": "🧃",
    ":cocktail:": "🍹",
    // New nature and weather
    ":tree:": "🌳",
    ":palm_tree:": "🌴",
    ":cactus:": "🌵",
    ":flower:": "🌸",
    ":rose:": "🌹",
    ":tulip:": "🌷",
    ":sunflower:": "🌻",
    ":seedling:": "🌱",
    ":herb:": "🌿",
    ":volcano:": "🌋",
    ":ocean:": "🌊",
    ":fog:": "🌫️",
    ":wind:": "💨",
    ":thunderstorm:": "⛈️",
    ":snowman:": "☃️",
    // New objects
    ":gift:": "🎁",
    ":balloon:": "🎈",
    ":party_popper:": "🎉",
    ":confetti_ball:": "🎊",
    ":microphone:": "🎤",
    ":guitar:": "🎸",
    ":drum:": "🥁",
    ":soccer:": "⚽",
    ":basketball:": "🏀",
    ":football:": "🏈",
    ":tennis:": "🎾",
    ":volleyball:": "🏐",
    ":car:": "🚗",
    ":bicycle:": "🚲",
    ":airplane:": "✈️",
    ":rocket:": "🚀",
    ":anchor:": "⚓",
    ":camera:": "📷",
    ":phone:": "📱",
    ":computer:": "💻",
    ":light_bulb:": "💡",
    ":book:": "📚",
    ":pencil:": "✏️",
    ":paperclip:": "📎",
    ":scissors:": "✂️",
    ":lock:": "🔒",
    ":key:": "🔑",
    ":hammer:": "🔨",
    ":wrench:": "🔧",
    // New symbols
    ":check_mark:": "✅",
    ":cross_mark:": "❌",
    ":exclamation:": "❗",
    ":question:": "❓",
    ":warning:": "⚠️",
    ":no_entry:": "⛔",
    ":recycle:": "♻️",
    ":infinity:": "♾️",
    ":musical_note:": "🎵",
    ":notes:": "🎶",
    ":yin_yang:": "☯️",
    ":peace:": "☮️",
    // New flags
    ":flag_un:": "🇺🇳",
    ":flag_checkered:": "🏁",
    ":flag_rainbow:": "🏳️‍🌈",
    ":flag_pirate:": "🏴‍☠️",
    // New miscellaneous
    ":skull:": "💀",
    ":ghost:": "👻",
    ":alien:": "👽",
    ":robot:": "🤖",
    ":poop:": "💩",
    ":clown:": "🤡",
    ":dragon:": "🐉",
    ":unicorn:": "🦄",
    ":mermaid:": "🧜‍♀️",
    ":fairy:": "🧚",
    ":crown:": "👑",
    ":ring:": "💍",
    ":gem:": "💎",
    ":money_bag:": "💰",
    ":hourglass:": "⌛",
    ":clock:": "🕒",
    ":thermometer:": "🌡️",
    ":battery:": "🔋"
};
  
  /**
   * Converts text emoji codes to Unicode emoji characters in a string like Discord's retarded emoji converter
   * @param {string} text - Input text containing emoji codes like :heart:
   * @returns {string} - Text with emoji codes replaced by actual emoji characters
   */
  function convertTextEmojis(text) {
    if (!text || typeof text !== 'string') {
      return text;
    }
    
    const emojiRegex = /:\w+:/g;
    
    return text.replace(emojiRegex, match => {
      return emojiMap[match] || match;
    });
}
  
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { convertTextEmojis, emojiMap };
}